const icons = {
    back: require('../assets/icons/back.png'),
    car: require('../assets/icons/car.png'),
    cutlery: require('../assets/icons/cutlery.png'),
    donut: require('../assets/icons/donut.png'),
    drink: require('../assets/icons/drink.png'),
    fries: require('../assets/icons/fries.png'),
    fire: require('../assets/icons/fire.png'),
    hamburger: require('../assets/icons/hamburger.png'),
    hotdog: require('../assets/icons/hotdog.png'),
    like: require('../assets/icons/like.png'),
    list: require('../assets/icons/list.png'),
    location: require('../assets/icons/location.png'),
    mastercard: require('../assets/icons/mastercard.png'),
    nearby: require('../assets/icons/nearby.png'),
    noodle: require('../assets/icons/noodle.png'),
    pizza: require('../assets/icons/pizza.png'),
    pin: require('../assets/icons/pin.png'),
    redpin: require('../assets/icons/red-pin.png'),
    rice_bowl: require('../assets/icons/rice-bowl.png'),
    salad: require('../assets/icons/salad.png'),
    search: require('../assets/icons/search.png'),
    star: require('../assets/icons/star.png'),
    sushi: require('../assets/icons/sushi.png'),
    user: require('../assets/icons/user.png'),
   basket: require('../assets/icons/shopping-basket.png'),
}

export default icons